//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDate, NSString, NSTimer, UIFont, UILabel;
@protocol APSKMBProgressHUDDelegate;

@interface APSKMBProgressHUD : UIView
+ (_Bool)hideHUDForView:(id)arg1 animated:(_Bool)arg2;
+ (id)showHUDAddedTo:(id)arg1 animated:(_Bool)arg2;

- (void)animationFinished:(id)arg1 finished:(_Bool)arg2 context:(void *)arg3;
@property int animationType; // @synthesize animationType;
- (void)cleanUp;
@property(retain) UIView *customView; // @synthesize customView;
@property __weak id <APSKMBProgressHUDDelegate> delegate; // @synthesize delegate;
@property(retain) UIFont *detailsLabelFont; // @synthesize detailsLabelFont;
@property(copy) NSString *detailsLabelText;
- (void)deviceOrientationDidChange:(id)arg1;
@property _Bool dimBackground; // @synthesize dimBackground;
- (void)done;
- (void)drawRect:(struct CGRect)arg1;
@property float graceTime; // @synthesize graceTime;
@property(retain) NSTimer *graceTimer; // @synthesize graceTimer;
- (void)handleGraceTimer:(id)arg1;
- (void)handleMinShowTimer:(id)arg1;
@property float height; // @synthesize height;
- (void)hide:(_Bool)arg1;
- (void)hide:(_Bool)arg1 afterDelay:(double)arg2;
- (void)hideDelayed:(id)arg1;
- (void)hideUsingAnimation:(_Bool)arg1;
@property(retain) UIView *indicator; // @synthesize indicator;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithView:(id)arg1;
- (id)initWithWindow:(id)arg1;
@property(getter=isSquare) _Bool square; // @synthesize square;
@property(retain) UIFont *labelFont; // @synthesize labelFont;
@property(copy) NSString *labelText;
- (void)layoutSubviews;
@property float margin; // @synthesize margin;
@property float minShowTime; // @synthesize minShowTime;
@property(retain) NSTimer *minShowTimer; // @synthesize minShowTimer;
@property struct CGSize minSize; // @synthesize minSize;
@property int mode;
@property float opacity; // @synthesize opacity;
@property float progress;
@property _Bool removeFromSuperViewOnHide; // @synthesize removeFromSuperViewOnHide;
- (void)removeFromSuperview;
@property(retain) NSDate *showStarted; // @synthesize showStarted;
@property _Bool taskInProgress; // @synthesize taskInProgress;
- (void)setTransformForCurrentOrientation:(_Bool)arg1;
@property float width; // @synthesize width;
@property float xOffset; // @synthesize xOffset;
@property float yOffset; // @synthesize yOffset;
- (void)show:(_Bool)arg1;
- (void)showUsingAnimation:(_Bool)arg1;
- (void)updateDetailsLabelText:(id)arg1;
- (void)updateIndicators;
- (void)updateLabelText:(id)arg1;
- (void)updateProgress;

@end

