//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTURLRequestOperation.h"

@class NSDictionary, NSString;

@interface DTRpcBaseOperation : DTURLRequestOperation
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(BLockWithObject)arg4;
@property(retain, nonatomic) NSDictionary *addHeaders; // @synthesize addHeaders=_addHeaders;
@property(retain, nonatomic) NSString *alertErr; // @synthesize alertErr=_alertErr;
- (_Bool)checkResultStatus:(id)arg1;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (id)emptyResponseError;
@property(nonatomic) _Bool isAMRPC; // @synthesize isAMRPC=_isAMRPC;
@property(nonatomic) _Bool isCDN; // @synthesize isCDN=_isCDN;
@property(nonatomic) _Bool isNSData; // @synthesize isNSData=_isNSData;
@property(nonatomic) _Bool isProtocolBuffers; // @synthesize isProtocolBuffers=_isProtocolBuffers;
@property(retain, nonatomic) NSDictionary *responseJSON; // @synthesize responseJSON=_responseJSON;
- (id)responseToDictionary:(id)arg1;
@property(retain, nonatomic) NSDictionary *resultJSON; // @synthesize resultJSON=_resultJSON;

@end

