//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTRpcBaseOperation.h"

@class DTRpcMethod, NSArray, NSCachedURLResponse, NSMutableDictionary, NSString, NSURLConnection, NSURLProtocol, NSURLRequest, NSURLSessionDataTask;

@interface DTRpcOperation : DTRpcBaseOperation
- (void)URLProtocol:(id)arg1 didFailWithError:(id)arg2;
- (void)URLProtocol:(id)arg1 didLoadData:(id)arg2;
- (void)URLProtocol:(id)arg1 didReceiveResponse:(id)arg2 cacheStoragePolicy:(unsigned long long)arg3;
- (void)URLProtocolDidFinishLoading:(id)arg1;
- (id)buildPBRequestDataWithMethod:(id)arg1 params:(id)arg2;
- (void)buildRequestDataWithMethod:(id)arg1 params:(id)arg2;
- (void)cacheResponseString;
@property(retain, nonatomic) NSCachedURLResponse *cachedResponse; // @synthesize cachedResponse=_cachedResponse;
@property(nonatomic) _Bool canResend; // @synthesize canResend=_canResend;
@property(retain, nonatomic) NSURLConnection *connection; // @synthesize connection=_connection;
@property(nonatomic) _Bool cookieReWrite; // @synthesize cookieReWrite=_cookieReWrite;
- (id)copy;
- (void)didFailWithError:(id)arg1;
- (void)didFinish;
- (void)didStart;
- (void)didURLProtocolFinishLoading;
- (void)didURLProtocolLoadData:(id)arg1;
- (void)didURLProtocolReceiveResponse:(id)arg1;
@property(retain, nonatomic) NSURLRequest *etagRequest; // @synthesize etagRequest=_etagRequest;
- (void)filRequestlValue:(id)arg1 contentType:(id)arg2 method:(id)arg3 params:(id)arg4;
@property(nonatomic) _Bool ignoreInterceptor; // @synthesize ignoreInterceptor=_ignoreInterceptor;
- (id)initWithURL:(id)arg1 method:(id)arg2 params:(id)arg3;
- (id)initWithURL:(id)arg1 method:(id)arg2 params:(id)arg3 amrpc:(_Bool)arg4 cdn:(_Bool)arg5;
- (id)initWithURL:(id)arg1 method:(id)arg2 params:(id)arg3 headerFields:(id)arg4;
- (id)initWithURL:(id)arg1 method:(id)arg2 params:(id)arg3 headerFields:(id)arg4 amrpc:(_Bool)arg5 cdn:(_Bool)arg6;
@property(nonatomic) _Bool isBlackListRPC; // @synthesize isBlackListRPC=_isBlackListRPC;
@property(nonatomic) _Bool isForegroundRPC; // @synthesize isForegroundRPC=_isForegroundRPC;
@property(nonatomic) _Bool isIgnoreNetStatus; // @synthesize isIgnoreNetStatus=_isIgnoreNetStatus;
@property(nonatomic) _Bool isLoginRPC; // @synthesize isLoginRPC=_isLoginRPC;
@property(nonatomic) _Bool isSDPYProtocol; // @synthesize isSDPYProtocol=_isSDPYProtocol;
@property(nonatomic) _Bool isSpecialChannelRPC; // @synthesize isSpecialChannelRPC=_isSpecialChannelRPC;
@property(nonatomic) long long logLevel; // @synthesize logLevel=_logLevel;
- (void)logVoidResultObject;
@property(retain, nonatomic) DTRpcMethod *method; // @synthesize method=_method;
@property(retain, nonatomic) NSArray *params; // @synthesize params=_params;
- (id)parsePBFromResultData;
@property(retain, nonatomic) NSURLProtocol *protocol; // @synthesize protocol=_protocol;
@property(retain, nonatomic) NSString *region; // @synthesize region=_region;
- (id)requestWithURL:(id)arg1 method:(id)arg2 params:(id)arg3 amrpc:(_Bool)arg4 cdn:(_Bool)arg5;
@property(copy, nonatomic) BLockWithObject responseBlock; // @synthesize responseBlock=_responseBlock;
@property(nonatomic) long long resultCode; // @synthesize resultCode=_resultCode;
@property(retain, nonatomic) id resultObject; // @synthesize resultObject=_resultObject;
@property(nonatomic) int retryCount; // @synthesize retryCount=_retryCount;
- (id)rpcOperationType;
- (void)rpcPrivateEncrypt;
@property(nonatomic) unsigned int rpcSeq; // @synthesize rpcSeq=_rpcSeq;
- (void)setResponseToPBIntoClass;
@property(nonatomic) _Bool shouldAppendCTUExtraParams; // @synthesize shouldAppendCTUExtraParams=_shouldAppendCTUExtraParams;
@property(nonatomic) _Bool shouldAppendTrafficControlParams; // @synthesize shouldAppendTrafficControlParams=_shouldAppendTrafficControlParams;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) DTRpcOperation *subOperation; // @synthesize subOperation=_subOperation;
@property(retain, nonatomic) NSURLSessionDataTask *task; // @synthesize task=_task;
@property(nonatomic) double timeoutInterval; // @synthesize timeoutInterval=_timeoutInterval;
@property(retain, nonatomic) NSMutableDictionary *userInfo; // @synthesize userInfo=_userInfo;
- (void)signRequest:(id)arg1;
- (void)start;
- (void)startConnection;
- (void)startWithoutInterceptor;
- (void)stopSendRPC;
- (void)toCDN:(id)arg1 cdn:(_Bool)arg2 reqURL:(id)arg3;

@end

